FH_template="fullAdder fh{} (.a({}),.b({}),.ci({}),.s({}),.co({}));\n"
assign_template="assign {} = {};\n"
RCA_template="adder #(.parallelism({}),.ARCH_TYPE({})) adder (.add1({}),.add0({}),.carry_in({}),.sum({}));\n"
product_bit="porduct[{}]"
product_bus="product[{}:{}]"
sums_bit="sums[{}][{}]"
sums_bus="sums[{}][{}:{}]"
carrys_bit="carrys[{}][{}]"
carrys_bus="carrys[{}][{}:{}]"
pps_bit="pps[{}][{}]"
